### ISSUE TITLE
fails to compile with 3.1.0

### ISSUE THREAD

**Issue by klehigh** [esnet/zeek_perfsonar_owamp#2]
The configure script no longer works due to the removal of bro-config .  Here is a hacked up configure script that should work on 3.0 and above : https://gist.github.com/klehigh/e9bfb566f4707bd8e45b7ff37902f97d

In addition, this error is raised :
/home/redacted/.bro-pkg/clones/package/zeek_perfsonar_owamp/src/Plugin.cc:14:20: error: allocation of incomplete type '::analyzer::Component'
                AddComponent(new ::analyzer::Component("OWAMP",
                                 ^~~~~~~~~~~~~~~~~~~~~
/home/redacted/src/zeek-3.1.0/src/analyzer/Tag.h:20:7: note: forward declaration of 'analyzer::Component'
class Component;
